<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jason Schmidberger">
<meta name="dcterms.date" content="2026-08-20">

<title>Internal duplication in the DehI dehalogenase family</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-496d54825f4a5d13459347af1c2e7183.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>
<script src="report_files/libs/quarto-diagram/mermaid.min.js"></script>
<script src="report_files/libs/quarto-diagram/mermaid-init.js"></script>
<link href="report_files/libs/quarto-diagram/mermaid.css" rel="stylesheet">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#summary" id="toc-summary" class="nav-link active" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#biological-question" id="toc-biological-question" class="nav-link" data-scroll-target="#biological-question">Biological question</a></li>
  <li><a href="#analysis-design" id="toc-analysis-design" class="nav-link" data-scroll-target="#analysis-design">Analysis design</a></li>
  <li><a href="#family-alignment-and-structural-reference" id="toc-family-alignment-and-structural-reference" class="nav-link" data-scroll-target="#family-alignment-and-structural-reference">Family alignment and structural reference</a>
  <ul class="collapse">
  <li><a href="#secondary-structure-context" id="toc-secondary-structure-context" class="nav-link" data-scroll-target="#secondary-structure-context">Secondary-structure context</a></li>
  </ul></li>
  <li><a href="#defining-and-extracting-the-repeats" id="toc-defining-and-extracting-the-repeats" class="nav-link" data-scroll-target="#defining-and-extracting-the-repeats">Defining and extracting the repeats</a></li>
  <li><a href="#hh-suite-profile-construction" id="toc-hh-suite-profile-construction" class="nav-link" data-scroll-target="#hh-suite-profile-construction">HH-suite profile construction</a></li>
  <li><a href="#n-terminal-versus-c-terminal-hhalign-result" id="toc-n-terminal-versus-c-terminal-hhalign-result" class="nav-link" data-scroll-target="#n-terminal-versus-c-terminal-hhalign-result">N-terminal versus C-terminal HHalign result</a>
  <ul class="collapse">
  <li><a href="#profile-profile-alignment" id="toc-profile-profile-alignment" class="nav-link" data-scroll-target="#profile-profile-alignment">Profile-profile alignment</a></li>
  </ul></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation">Interpretation</a>
  <ul class="collapse">
  <li><a href="#statistical-qualification" id="toc-statistical-qualification" class="nav-link" data-scroll-target="#statistical-qualification">Statistical qualification</a></li>
  </ul></li>
  <li><a href="#robustness-checks-and-next-analyses" id="toc-robustness-checks-and-next-analyses" class="nav-link" data-scroll-target="#robustness-checks-and-next-analyses">Robustness checks and next analyses</a></li>
  <li><a href="#reproducibility-and-downloads" id="toc-reproducibility-and-downloads" class="nav-link" data-scroll-target="#reproducibility-and-downloads">Reproducibility and downloads</a>
  <ul class="collapse">
  <li><a href="#scripts" id="toc-scripts" class="nav-link" data-scroll-target="#scripts">Scripts</a></li>
  <li><a href="#alignments-and-sequences" id="toc-alignments-and-sequences" class="nav-link" data-scroll-target="#alignments-and-sequences">Alignments and sequences</a></li>
  <li><a href="#profiles-and-comparison-output" id="toc-profiles-and-comparison-output" class="nav-link" data-scroll-target="#profiles-and-comparison-output">Profiles and comparison output</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Internal duplication in the DehI dehalogenase family</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">A 3BJX-guided sequence and profile-HMM analysis</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jason Schmidberger </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 20, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>The configuration-inverting 2-haloacid dehalogenase DehI has two structurally similar regions of approximately 130 amino acids. This analysis tests whether the two regions retain detectable sequence homology consistent with an ancient tandem duplication and fusion.</p>
<p>The N- and C-terminal regions were defined using the experimentally determined DehI structure 3BJX, extracted from a 69-sequence family alignment, converted into separate HH-suite profile hidden Markov models, and compared using HHalign. The profiles align over nearly their entire lengths with <strong>99.54% HHalign probability</strong>, an <strong>E-value of 2.9 × 10<sup>-23</sup></strong>, and <strong>17% direct sequence identity</strong>. The combination of low identity, strong profile-profile support, and broad alignment coverage is consistent with remote homology between the two DehI repeats.</p>
<div class="callout callout-style-default callout-important callout-titled" title="Principal result">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Principal result
</div>
</div>
<div class="callout-body-container callout-body">
<p>The N- and C-terminal profiles align across 108 columns: 88% of the N-terminal model and 96% of the C-terminal model. This is a domain-scale match rather than a short conserved motif.</p>
</div>
</div>
</section>
<section id="biological-question" class="level2">
<h2 class="anchored" data-anchor-id="biological-question">Biological question</h2>
<p>DehI from <em>Pseudomonas putida</em> PP3 is an unusual α-helical dehalogenase with a deep Stevedore knot. Its monomer contains two regions with closely similar structures but low pairwise sequence identity. The original structural study described two approximately 130-residue domains with about 16% sequence identity (<a href="https://www.rcsb.org/structure/3BJX">PDB 3BJX</a>; <a href="https://doi.org/10.1016/j.jmb.2008.02.035">DOI: 10.1016/j.jmb.2008.02.035</a>). A later topology analysis interpreted these regions as likely products of tandem sequence duplication and described the proline-rich arc connecting them (<a href="https://doi.org/10.1371/journal.pcbi.1000731">King <em>et al.</em>, 2010</a>).</p>
<p>The specific question addressed here is:</p>
<blockquote class="blockquote">
<p>Does a profile-profile comparison of the DehI N- and C-terminal families recover statistically strong, domain-scale sequence homology after the linker is excluded?</p>
</blockquote>
</section>
<section id="analysis-design" class="level2">
<h2 class="anchored" data-anchor-id="analysis-design">Analysis design</h2>
<div class="cell" data-layout-align="default">
<div class="cell-output-display">
<div>
<p></p><figure class="figure"><p></p>
<div>
<pre class="mermaid mermaid-js">flowchart LR
    A[DehI family&lt;br&gt;core MSA] --&gt; B[Map 3BJX&lt;br&gt;structural boundary]
    B --&gt; C[N-terminal MSA&lt;br&gt;residues 1–129]
    B --&gt; D[C-terminal MSA&lt;br&gt;residues 162–296]
    B -.-&gt; E[Exclude linker&lt;br&gt;residues 130–161]
    C --&gt; F[N-terminal HHM]
    D --&gt; G[C-terminal HHM]
    F --&gt; H[HHalign&lt;br&gt;profile–profile comparison]
    G --&gt; H
</pre>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>
<p>The workflow deliberately separates computation from presentation. Alignment splitting and HH-suite profile construction are performed by version-controlled scripts. This document reads the resulting files; it does not rerun HH-suite during website rendering.</p>
</section>
<section id="family-alignment-and-structural-reference" class="level2">
<h2 class="anchored" data-anchor-id="family-alignment-and-structural-reference">Family alignment and structural reference</h2>
<p>The input was the 69-sequence aligned FASTA file <a href="results/dehi_core_msa.fasta"><code>dehi_core_msa.fasta</code></a>. The first record is the 3BJX chain-A reference. Its aligned sequence contains a 15-residue recombinant N-terminal expression tag followed by native DehI residues 1–296.</p>
<div id="tbl-input-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-input-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Input family-alignment summary.
</figcaption>
<div aria-describedby="tbl-input-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Property</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Family sequences</td>
<td style="text-align: right;">69</td>
</tr>
<tr class="even">
<td>Alignment columns</td>
<td style="text-align: right;">384</td>
</tr>
<tr class="odd">
<td>3BJX aligned residues</td>
<td style="text-align: right;">311</td>
</tr>
<tr class="even">
<td>3BJX expression-tag residues</td>
<td style="text-align: right;">15</td>
</tr>
<tr class="odd">
<td>3BJX native residues</td>
<td style="text-align: right;">296</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="secondary-structure-context" class="level3">
<h3 class="anchored" data-anchor-id="secondary-structure-context">Secondary-structure context</h3>
<p>The deposited <code>HELIX</code> records from 3BJX were mapped through the gaps in the 3BJX alignment row. Red rounded bars denote helices. The figure shows the first 20 family members for legibility; the domain splitting and HHM construction use all 69 sequences.</p>
<div id="fig-msa-ss" class="quarto-float quarto-figure quarto-figure-center anchored" alt="Wrapped DehI multiple-sequence alignment with the 3BJX secondary structure displayed as red helix bars above each block.">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-msa-ss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="dehi_3BJX_secondary_structure.png" class="img-fluid figure-img" style="width:100.0%" alt="Wrapped DehI multiple-sequence alignment with the 3BJX secondary structure displayed as red helix bars above each block.">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-msa-ss-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: 3BJX secondary structure mapped onto a representative subset of the DehI family alignment.
</figcaption>
</figure>
</div>
</section>
</section>
<section id="defining-and-extracting-the-repeats" class="level2">
<h2 class="anchored" data-anchor-id="defining-and-extracting-the-repeats">Defining and extracting the repeats</h2>
<p>The last long helix of the N-terminal repeat ends at 3BJX residue 129. A proline-rich region occupies residues 130–161, and the next repeat begins at residue 162 with a short 3<sub>10</sub> helix followed by the first long C-terminal helix. The linker is therefore 32 residues by these structure-defined bounds, corresponding to the approximately 30-residue linker described informally.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Region</th>
<th style="text-align: right;">Native 3BJX residues</th>
<th>Treatment</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>N-terminal repeat</td>
<td style="text-align: right;">1–129</td>
<td>Retained</td>
</tr>
<tr class="even">
<td>Proline-rich linker</td>
<td style="text-align: right;">130–161</td>
<td>Excluded</td>
</tr>
<tr class="odd">
<td>C-terminal repeat</td>
<td style="text-align: right;">162–296</td>
<td>Retained</td>
</tr>
</tbody>
</table>
<p>The boundaries were mapped from native 3BJX residue numbers to MSA columns. The same columns were then extracted from every family member. All-gap columns were removed independently from each resulting alignment. The procedure is implemented in <a href="split_dehi_msa.py"><code>split_dehi_msa.py</code></a>.</p>
<div id="tbl-split-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-split-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Structure-guided split of the DehI family alignment.
</figcaption>
<div aria-describedby="tbl-split-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Region</th>
<th style="text-align: right;">3BJX residues</th>
<th style="text-align: right;">Source MSA columns</th>
<th style="text-align: right;">Output columns</th>
<th style="text-align: right;">Sequences</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>N</td>
<td style="text-align: right;">1–129</td>
<td style="text-align: right;">16–154</td>
<td style="text-align: right;">139</td>
<td style="text-align: right;">69</td>
</tr>
<tr class="even">
<td>Linker excluded</td>
<td style="text-align: right;">130–161</td>
<td style="text-align: right;">155–217</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">—</td>
</tr>
<tr class="odd">
<td>C</td>
<td style="text-align: right;">162–296</td>
<td style="text-align: right;">218–384</td>
<td style="text-align: right;">167</td>
<td style="text-align: right;">69</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The N-terminal output has 139 aligned columns and the C-terminal output has 167. The ungapped 3BJX fragments contain 129 and 135 residues, respectively. All 69 input records are represented in both outputs.</p>
</section>
<section id="hh-suite-profile-construction" class="level2">
<h2 class="anchored" data-anchor-id="hh-suite-profile-construction">HH-suite profile construction</h2>
<p>HH-suite was chosen because HHalign directly compares profile HMMs and is designed to detect remote protein homology through alignment-to-alignment or HMM-to-HMM comparison (<a href="https://github.com/soedinglab/hh-suite">HH-suite documentation</a>; <a href="https://doi.org/10.1186/s12859-019-3019-7">Steinegger <em>et al.</em>, 2019</a>).</p>
<p>Each split FASTA alignment was converted to A3M format. A column was designated as a match state when fewer than 50% of sequences contained a gap (<code>-M 50</code>). Columns not meeting this condition were represented as insert states. HHmake then applied its standard sequence filtering and weighting before constructing each HHM.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="ex">reformat.pl</span> fas a3m results/dehi_N_terminal_msa.fasta <span class="dt">\</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  results/dehi_N_terminal.a3m <span class="at">-M</span> 50</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="ex">reformat.pl</span> fas a3m results/dehi_C_terminal_msa.fasta <span class="dt">\</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  results/dehi_C_terminal.a3m <span class="at">-M</span> 50</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="ex">hhmake</span> <span class="at">-i</span> results/dehi_N_terminal.a3m <span class="dt">\</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">-o</span> results/dehi_N_terminal.hhm <span class="at">-name</span> DehI_N_terminal</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="ex">hhmake</span> <span class="at">-i</span> results/dehi_C_terminal.a3m <span class="dt">\</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">-o</span> results/dehi_C_terminal.hhm <span class="at">-name</span> DehI_C_terminal</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-profile-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-profile-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Properties of the two HH-suite profiles.
</figcaption>
<div aria-describedby="tbl-profile-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Profile</th>
<th style="text-align: right;">Match states</th>
<th style="text-align: right;">Sequences retained</th>
<th style="text-align: right;">Effective sequences</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DehI N-terminal</td>
<td style="text-align: right;">123</td>
<td style="text-align: right;">68/69</td>
<td style="text-align: right;">5.5</td>
</tr>
<tr class="even">
<td>DehI C-terminal</td>
<td style="text-align: right;">113</td>
<td style="text-align: right;">68/69</td>
<td style="text-align: right;">6.0</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>HHmake retained 68 of 69 sequences in each model after its default redundancy and quality filters. The effective sequence counts (<code>Neff</code>) of 5.5 and 6.0 are much smaller than the raw sequence count because related sequences do not contribute as independent observations.</p>
</section>
<section id="n-terminal-versus-c-terminal-hhalign-result" class="level2">
<h2 class="anchored" data-anchor-id="n-terminal-versus-c-terminal-hhalign-result">N-terminal versus C-terminal HHalign result</h2>
<p>The two precomputed HHMs were compared directly:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="ex">hhalign</span> <span class="dt">\</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">-i</span> results/dehi_N_terminal.hhm <span class="dt">\</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">-t</span> results/dehi_C_terminal.hhm <span class="dt">\</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">-o</span> results/dehi_N_vs_C.hhr <span class="dt">\</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">-Oa3m</span> results/dehi_N_vs_C.a3m <span class="dt">\</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">-atab</span> results/dehi_N_vs_C.tsv</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="tbl-hhalign-summary" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-hhalign-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: HHalign profile-profile comparison.
</figcaption>
<div aria-describedby="tbl-hhalign-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>HHalign probability</td>
<td style="text-align: right;">99.54%</td>
</tr>
<tr class="even">
<td>E-value</td>
<td style="text-align: right;">2.9 × 10<sup>-23</sup></td>
</tr>
<tr class="odd">
<td>Profile score</td>
<td style="text-align: right;">124.39 bits</td>
</tr>
<tr class="even">
<td>Aligned columns</td>
<td style="text-align: right;">108</td>
</tr>
<tr class="odd">
<td>Direct identity</td>
<td style="text-align: right;">17%</td>
</tr>
<tr class="even">
<td>Profile similarity</td>
<td style="text-align: right;">0.123</td>
</tr>
<tr class="odd">
<td>Sum of posterior probabilities</td>
<td style="text-align: right;">94.6</td>
</tr>
<tr class="even">
<td>N-profile coverage</td>
<td style="text-align: right;">87.8%</td>
</tr>
<tr class="odd">
<td>C-profile coverage</td>
<td style="text-align: right;">95.6%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The alignment spans N-profile match states 5–113 and C-profile match states 2–112. It therefore covers most of both models rather than selecting a small highly conserved segment. The 17% direct identity lies in the range where pairwise sequence comparison alone is generally difficult, while the profile score remains strong because residue preferences and gap patterns are aggregated across the family.</p>
<section id="profile-profile-alignment" class="level3">
<h3 class="anchored" data-anchor-id="profile-profile-alignment">Profile-profile alignment</h3>
<p>The following is the consensus and 3BJX portion of the HHalign output. Digits in the <code>Confidence</code> lines are posterior alignment confidence on a 0–9 scale.</p>
<pre class="text"><code>Q 3BJX       12 QLDVSGEMESTYEDIRLTLRVPWVAFGCRVLATFPGYLPLAWRR.SAEALITRYAEQAADELRERSLLNIGPLPNL-K-E 88 (129)
Q Consensus   5 e~eA~g~~~~vY~DIk~tLrVP~Vn~ifRtlA~yp~fl~~~W~~.~rP~~~T~~fe~aA~~lR~~~~~~~~~~~~~-~-~ 81 (123)
                +.++.+.++++|+|||+++|.|.||..+|+||+||+||..+|+. +||..+|.+|++++++++..+...+...+-+ . .
T Consensus   2 ~~~~~~~~~~l~~dI~~~h~~~~v~SdYR~LA~wP~~L~~~W~~.LkP~i~s~~y~~~~~~l~~~A~~~v~~lP~~v~l~ 80 (113)
T 3BJX        2 ATKASTEVQGLLKRVADLHYHHGPASDFQALANWPKVLQIVTDEvLAPVARTEQYDAKSRELVTRARELVRGLPGSAGVQ 81 (135)
Confidence      56889999999999999999999999999999999999999999 9999999999999999999888877765332 1 1

Q 3BJX       89 --RLYAAGFDDGEIEKVRRVLYAFNYGNPKYLL 119 (129)
Q Consensus  82 ~-~~~~~~~~~~~~~~ir~~l~~f~~vnPklLl 113 (123)
                 . .+.+.+ ++.++++|.+.+..|...-|-++|
T Consensus  81 ~~~L~~~~-~~~~i~~i~~l~~~F~~~lp~Lil 112 (113)
T 3BJX       82 RSELMSML-TPNELAGLTGVLFMYQRFIADITI 113 (135)
Confidence      1 555555 899999999999999988877654</code></pre>
</section>
</section>
<section id="interpretation" class="level2">
<h2 class="anchored" data-anchor-id="interpretation">Interpretation</h2>
<p>Three features make this result supportive of internal homology:</p>
<ol type="1">
<li><strong>High profile probability.</strong> HHalign assigns a 99.54% probability to the N/C relationship.</li>
<li><strong>Domain-scale coverage.</strong> The 108 aligned columns cover 88% of the N model and 96% of the C model.</li>
<li><strong>Remote rather than trivial similarity.</strong> Direct identity is only 17%, yet conserved residue patterns remain detectable when information is combined across 69 family members.</li>
</ol>
<p>Together with the near-identical structural folds reported for 3BJX, this is consistent with the proposal that an ancestral domain duplicated in tandem and the two copies subsequently diverged while remaining fused in DehI.</p>
<div class="callout callout-style-default callout-note callout-titled" title="What the result does not prove">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What the result does not prove
</div>
</div>
<div class="callout-body-container callout-body">
<p>HHalign measures compatibility between two profile models. It does not by itself date the duplication, identify the ancestral free-standing family, or exclude every alternative evolutionary scenario. Structural correspondence, taxonomic distribution, conserved catalytic residues, and comparisons with external families provide independent evidence.</p>
</div>
</div>
<section id="statistical-qualification" class="level3">
<h3 class="anchored" data-anchor-id="statistical-qualification">Statistical qualification</h3>
<p>Only one template HMM was searched (<code>Searched_HMMs 1</code>). Consequently, the reported E-value and P-value are identical (<code>2.9 × 10^-23^</code>); this is not an E-value corrected for a large profile database. The probability, score, and especially the broad alignment coverage remain directly informative for this pre-specified N-versus-C comparison.</p>
<p>Secondary structure was not included in the HHalign score (<code>SS = 0</code>, reported as <code>missing dssp</code>). This makes the profile match a sequence-derived result rather than one driven by the known structural similarity.</p>
</section>
</section>
<section id="robustness-checks-and-next-analyses" class="level2">
<h2 class="anchored" data-anchor-id="robustness-checks-and-next-analyses">Robustness checks and next analyses</h2>
<p>The following tests would strengthen the evolutionary interpretation:</p>
<ul>
<li>Rebuild both profiles after removing 3BJX and repeat the comparison, ensuring that the structural reference is not driving the result.</li>
<li>Repeat profile construction with match-state thresholds of 30%, 50%, and 70% gaps and compare the aligned cores.</li>
<li>Construct independent CMD and AhpD HHMs, then compare DehI-N and DehI-C to each external family.</li>
<li>Search both DehI profiles against the same curated HH-suite database and test whether their strongest domain-level matches overlap.</li>
<li>Map conserved aligned profile positions back onto the 3BJX structure and determine whether they occupy corresponding structural environments.</li>
</ul>
<p>The four most direct cross-family comparisons are:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Query profile</th>
<th>Template profile</th>
<th>Question</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>DehI-N</td>
<td>CMD</td>
<td>Does the N repeat resemble a free-standing CMD-like fold?</td>
</tr>
<tr class="even">
<td>DehI-C</td>
<td>CMD</td>
<td>Does the C repeat show the same relationship?</td>
</tr>
<tr class="odd">
<td>DehI-N</td>
<td>AhpD</td>
<td>Does the N repeat resemble the AhpD family?</td>
</tr>
<tr class="even">
<td>DehI-C</td>
<td>AhpD</td>
<td>Does the C repeat show the same relationship?</td>
</tr>
</tbody>
</table>
<p>Agreement across both halves and an external family would provide stronger evidence about the ancestry of the duplicated unit than the internal N/C result alone.</p>
</section>
<section id="reproducibility-and-downloads" class="level2">
<h2 class="anchored" data-anchor-id="reproducibility-and-downloads">Reproducibility and downloads</h2>
<p>The report uses precomputed HH-suite output so that the website can be rendered without installing native bioinformatics software. The Python dependencies are managed by <code>uv</code>; HH-suite 3 is required only when regenerating the profiles.</p>
<section id="scripts" class="level3">
<h3 class="anchored" data-anchor-id="scripts">Scripts</h3>
<ul>
<li><a href="split_dehi_msa.py"><code>split_dehi_msa.py</code></a> — map the 3BJX boundaries through the family MSA and extract both repeats.</li>
<li><a href="build_dehi_hhsuite_profiles.sh"><code>build_dehi_hhsuite_profiles.sh</code></a> — convert the alignments to A3M, construct both HHMs, and run HHalign.</li>
</ul>
</section>
<section id="alignments-and-sequences" class="level3">
<h3 class="anchored" data-anchor-id="alignments-and-sequences">Alignments and sequences</h3>
<ul>
<li><a href="results/dehi_core_msa.fasta">Full DehI core MSA</a></li>
<li><a href="results/dehi_N_terminal_msa.fasta">N-terminal aligned FASTA</a></li>
<li><a href="results/dehi_C_terminal_msa.fasta">C-terminal aligned FASTA</a></li>
<li><a href="results/dehi_N_terminal.fasta">N-terminal ungapped FASTA</a></li>
<li><a href="results/dehi_C_terminal.fasta">C-terminal ungapped FASTA</a></li>
<li><a href="results/dehi_N_terminal.a3m">N-terminal A3M</a></li>
<li><a href="results/dehi_C_terminal.a3m">C-terminal A3M</a></li>
</ul>
</section>
<section id="profiles-and-comparison-output" class="level3">
<h3 class="anchored" data-anchor-id="profiles-and-comparison-output">Profiles and comparison output</h3>
<ul>
<li><a href="results/dehi_N_terminal.hhm">N-terminal HHM</a></li>
<li><a href="results/dehi_C_terminal.hhm">C-terminal HHM</a></li>
<li><a href="results/dehi_N_vs_C.hhr">HHalign report</a></li>
<li><a href="results/dehi_N_vs_C.a3m">HHalign pairwise A3M</a></li>
<li><a href="results/dehi_N_vs_C.tsv">HHalign per-column table</a></li>
<li><a href="results/dehi_terminal_split_report.tsv">Domain-splitting report</a></li>
</ul>
<p>To regenerate the derived files locally:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python split_dehi_msa.py</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="ex">./build_dehi_hhsuite_profiles.sh</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> render report.qmd</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<!-- -->

</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const cellDetails = window.document.querySelectorAll(".cell details.code-fold");
        for (let i=0; i<cellDetails.length; i++) {
          const details = cellDetails[i];
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell div.sourceCode.cell-code");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Internal duplication in the DehI dehalogenase family"</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "A 3BJX-guided sequence and profile-HMM analysis"</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="an">author:</span><span class="co"> "Jason Schmidberger"</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> last-modified</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="an">format:</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">  html:</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">    theme: cosmo</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">    toc: true</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co">    toc-depth: 3</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">    code-fold: true</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co">    code-summary: "Show analysis code"</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co">    code-tools: true</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co">    code-copy: true</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="co">    fig-responsive: true</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="co">    link-external-newwindow: true</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a><span class="co">    smooth-scroll: true</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a><span class="co">  enabled: false</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a><span class="an">resources:</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a><span class="co">  - dehi_3BJX_secondary_structure.png</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a><span class="co">  - split_dehi_msa.py</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a><span class="co">  - build_dehi_hhsuite_profiles.sh</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="co">  - results/dehi_core_msa.fasta</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="co">  - results/dehi_N_terminal_msa.fasta</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="co">  - results/dehi_C_terminal_msa.fasta</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="co">  - results/dehi_N_terminal.fasta</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="co">  - results/dehi_C_terminal.fasta</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="co">  - results/dehi_N_terminal.a3m</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="co">  - results/dehi_C_terminal.a3m</span></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a><span class="co">  - results/dehi_N_terminal.hhm</span></span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a><span class="co">  - results/dehi_C_terminal.hhm</span></span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a><span class="co">  - results/dehi_N_vs_C.hhr</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a><span class="co">  - results/dehi_N_vs_C.a3m</span></span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a><span class="co">  - results/dehi_N_vs_C.tsv</span></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a><span class="co">  - results/dehi_terminal_split_report.tsv</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a><span class="fu">## Summary</span></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>The configuration-inverting 2-haloacid dehalogenase DehI has two structurally</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>similar regions of approximately 130 amino acids. This analysis tests whether</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>the two regions retain detectable sequence homology consistent with an ancient</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a>tandem duplication and fusion.</span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>The N- and C-terminal regions were defined using the experimentally determined</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>DehI structure 3BJX, extracted from a 69-sequence family alignment, converted</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>into separate HH-suite profile hidden Markov models, and compared using</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>HHalign. The profiles align over nearly their entire lengths with **99.54%</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>HHalign probability**, an **E-value of 2.9 × 10^-23^**, and **17% direct</span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>sequence identity**. The combination of low identity, strong profile-profile</span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>support, and broad alignment coverage is consistent with remote homology</span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>between the two DehI repeats.</span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-55"><a href="#cb5-55" aria-hidden="true" tabindex="-1"></a>::: {.callout-important title="Principal result"}</span>
<span id="cb5-56"><a href="#cb5-56" aria-hidden="true" tabindex="-1"></a>The N- and C-terminal profiles align across 108 columns: 88% of the N-terminal</span>
<span id="cb5-57"><a href="#cb5-57" aria-hidden="true" tabindex="-1"></a>model and 96% of the C-terminal model. This is a domain-scale match rather than</span>
<span id="cb5-58"><a href="#cb5-58" aria-hidden="true" tabindex="-1"></a>a short conserved motif.</span>
<span id="cb5-59"><a href="#cb5-59" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb5-60"><a href="#cb5-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-61"><a href="#cb5-61" aria-hidden="true" tabindex="-1"></a><span class="fu">## Biological question</span></span>
<span id="cb5-62"><a href="#cb5-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-63"><a href="#cb5-63" aria-hidden="true" tabindex="-1"></a>DehI from *Pseudomonas putida* PP3 is an unusual α-helical dehalogenase with a</span>
<span id="cb5-64"><a href="#cb5-64" aria-hidden="true" tabindex="-1"></a>deep Stevedore knot. Its monomer contains two regions with closely similar</span>
<span id="cb5-65"><a href="#cb5-65" aria-hidden="true" tabindex="-1"></a>structures but low pairwise sequence identity. The original structural study</span>
<span id="cb5-66"><a href="#cb5-66" aria-hidden="true" tabindex="-1"></a>described two approximately 130-residue domains with about 16% sequence</span>
<span id="cb5-67"><a href="#cb5-67" aria-hidden="true" tabindex="-1"></a>identity (<span class="co">[</span><span class="ot">PDB 3BJX</span><span class="co">](https://www.rcsb.org/structure/3BJX)</span>;</span>
<span id="cb5-68"><a href="#cb5-68" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">DOI: 10.1016/j.jmb.2008.02.035</span><span class="co">](https://doi.org/10.1016/j.jmb.2008.02.035)</span>).</span>
<span id="cb5-69"><a href="#cb5-69" aria-hidden="true" tabindex="-1"></a>A later topology analysis interpreted these regions as likely products of</span>
<span id="cb5-70"><a href="#cb5-70" aria-hidden="true" tabindex="-1"></a>tandem sequence duplication and described the proline-rich arc connecting them</span>
<span id="cb5-71"><a href="#cb5-71" aria-hidden="true" tabindex="-1"></a>(<span class="co">[</span><span class="ot">King *et al.*, 2010</span><span class="co">](https://doi.org/10.1371/journal.pcbi.1000731)</span>).</span>
<span id="cb5-72"><a href="#cb5-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-73"><a href="#cb5-73" aria-hidden="true" tabindex="-1"></a>The specific question addressed here is:</span>
<span id="cb5-74"><a href="#cb5-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-75"><a href="#cb5-75" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; Does a profile-profile comparison of the DehI N- and C-terminal families</span></span>
<span id="cb5-76"><a href="#cb5-76" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; recover statistically strong, domain-scale sequence homology after the linker</span></span>
<span id="cb5-77"><a href="#cb5-77" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; is excluded?</span></span>
<span id="cb5-78"><a href="#cb5-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-79"><a href="#cb5-79" aria-hidden="true" tabindex="-1"></a><span class="fu">## Analysis design</span></span>
<span id="cb5-80"><a href="#cb5-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-83"><a href="#cb5-83" aria-hidden="true" tabindex="-1"></a><span class="in">```{mermaid}</span></span>
<span id="cb5-84"><a href="#cb5-84" aria-hidden="true" tabindex="-1"></a>flowchart LR</span>
<span id="cb5-85"><a href="#cb5-85" aria-hidden="true" tabindex="-1"></a>    A[DehI family&lt;br&gt;core MSA] --&gt; B[Map <span class="dv">3</span>BJX&lt;br&gt;structural boundary]</span>
<span id="cb5-86"><a href="#cb5-86" aria-hidden="true" tabindex="-1"></a>    B --&gt; C[N-terminal MSA&lt;br&gt;residues <span class="dv">1</span>–<span class="dv">129</span>]</span>
<span id="cb5-87"><a href="#cb5-87" aria-hidden="true" tabindex="-1"></a>    B --&gt; D[C-terminal MSA&lt;br&gt;residues <span class="dv">162</span>–<span class="dv">296</span>]</span>
<span id="cb5-88"><a href="#cb5-88" aria-hidden="true" tabindex="-1"></a>    B -.-&gt; E[Exclude linker&lt;br&gt;residues <span class="dv">130</span>–<span class="dv">161</span>]</span>
<span id="cb5-89"><a href="#cb5-89" aria-hidden="true" tabindex="-1"></a>    C --&gt; F[N-terminal HHM]</span>
<span id="cb5-90"><a href="#cb5-90" aria-hidden="true" tabindex="-1"></a>    D --&gt; G[C-terminal HHM]</span>
<span id="cb5-91"><a href="#cb5-91" aria-hidden="true" tabindex="-1"></a>    F --&gt; H[HHalign&lt;br&gt;profile–profile comparison]</span>
<span id="cb5-92"><a href="#cb5-92" aria-hidden="true" tabindex="-1"></a>    G --&gt; H</span>
<span id="cb5-93"><a href="#cb5-93" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-94"><a href="#cb5-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-95"><a href="#cb5-95" aria-hidden="true" tabindex="-1"></a>The workflow deliberately separates computation from presentation. Alignment</span>
<span id="cb5-96"><a href="#cb5-96" aria-hidden="true" tabindex="-1"></a>splitting and HH-suite profile construction are performed by version-controlled</span>
<span id="cb5-97"><a href="#cb5-97" aria-hidden="true" tabindex="-1"></a>scripts. This document reads the resulting files; it does not rerun HH-suite</span>
<span id="cb5-98"><a href="#cb5-98" aria-hidden="true" tabindex="-1"></a>during website rendering.</span>
<span id="cb5-99"><a href="#cb5-99" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-100"><a href="#cb5-100" aria-hidden="true" tabindex="-1"></a><span class="fu">## Family alignment and structural reference</span></span>
<span id="cb5-101"><a href="#cb5-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-102"><a href="#cb5-102" aria-hidden="true" tabindex="-1"></a>The input was the 69-sequence aligned FASTA file</span>
<span id="cb5-103"><a href="#cb5-103" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">`dehi_core_msa.fasta`</span><span class="co">](results/dehi_core_msa.fasta)</span>. The first record is the</span>
<span id="cb5-104"><a href="#cb5-104" aria-hidden="true" tabindex="-1"></a>3BJX chain-A reference. Its aligned sequence contains a 15-residue recombinant</span>
<span id="cb5-105"><a href="#cb5-105" aria-hidden="true" tabindex="-1"></a>N-terminal expression tag followed by native DehI residues 1–296.</span>
<span id="cb5-106"><a href="#cb5-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-107"><a href="#cb5-107" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Property <span class="pp">|</span> Value <span class="pp">|</span></span>
<span id="cb5-108"><a href="#cb5-108" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|</span></span>
<span id="cb5-109"><a href="#cb5-109" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Family sequences <span class="pp">|</span> 69 <span class="pp">|</span></span>
<span id="cb5-110"><a href="#cb5-110" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Alignment columns <span class="pp">|</span> 384 <span class="pp">|</span></span>
<span id="cb5-111"><a href="#cb5-111" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3BJX aligned residues <span class="pp">|</span> 311 <span class="pp">|</span></span>
<span id="cb5-112"><a href="#cb5-112" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3BJX expression-tag residues <span class="pp">|</span> 15 <span class="pp">|</span></span>
<span id="cb5-113"><a href="#cb5-113" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> 3BJX native residues <span class="pp">|</span> 296 <span class="pp">|</span></span>
<span id="cb5-114"><a href="#cb5-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-115"><a href="#cb5-115" aria-hidden="true" tabindex="-1"></a>: Input family-alignment summary. {#tbl-input-summary}</span>
<span id="cb5-116"><a href="#cb5-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-117"><a href="#cb5-117" aria-hidden="true" tabindex="-1"></a><span class="fu">### Secondary-structure context</span></span>
<span id="cb5-118"><a href="#cb5-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-119"><a href="#cb5-119" aria-hidden="true" tabindex="-1"></a>The deposited <span class="in">`HELIX`</span> records from 3BJX were mapped through the gaps in the</span>
<span id="cb5-120"><a href="#cb5-120" aria-hidden="true" tabindex="-1"></a>3BJX alignment row. Red rounded bars denote helices. The figure shows the first</span>
<span id="cb5-121"><a href="#cb5-121" aria-hidden="true" tabindex="-1"></a>20 family members for legibility; the domain splitting and HHM construction use</span>
<span id="cb5-122"><a href="#cb5-122" aria-hidden="true" tabindex="-1"></a>all 69 sequences.</span>
<span id="cb5-123"><a href="#cb5-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-124"><a href="#cb5-124" aria-hidden="true" tabindex="-1"></a><span class="al">![3BJX secondary structure mapped onto a representative subset of the DehI family alignment.](dehi_3BJX_secondary_structure.png)</span>{#fig-msa-ss fig-alt="Wrapped DehI multiple-sequence alignment with the 3BJX secondary structure displayed as red helix bars above each block." width=100%}</span>
<span id="cb5-125"><a href="#cb5-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-126"><a href="#cb5-126" aria-hidden="true" tabindex="-1"></a><span class="fu">## Defining and extracting the repeats</span></span>
<span id="cb5-127"><a href="#cb5-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-128"><a href="#cb5-128" aria-hidden="true" tabindex="-1"></a>The last long helix of the N-terminal repeat ends at 3BJX residue 129. A</span>
<span id="cb5-129"><a href="#cb5-129" aria-hidden="true" tabindex="-1"></a>proline-rich region occupies residues 130–161, and the next repeat begins at</span>
<span id="cb5-130"><a href="#cb5-130" aria-hidden="true" tabindex="-1"></a>residue 162 with a short 3~10~ helix followed by the first long C-terminal</span>
<span id="cb5-131"><a href="#cb5-131" aria-hidden="true" tabindex="-1"></a>helix. The linker is therefore 32 residues by these structure-defined bounds,</span>
<span id="cb5-132"><a href="#cb5-132" aria-hidden="true" tabindex="-1"></a>corresponding to the approximately 30-residue linker described informally.</span>
<span id="cb5-133"><a href="#cb5-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-134"><a href="#cb5-134" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Region <span class="pp">|</span> Native 3BJX residues <span class="pp">|</span> Treatment <span class="pp">|</span></span>
<span id="cb5-135"><a href="#cb5-135" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---|</span></span>
<span id="cb5-136"><a href="#cb5-136" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> N-terminal repeat <span class="pp">|</span> 1–129 <span class="pp">|</span> Retained <span class="pp">|</span></span>
<span id="cb5-137"><a href="#cb5-137" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Proline-rich linker <span class="pp">|</span> 130–161 <span class="pp">|</span> Excluded <span class="pp">|</span></span>
<span id="cb5-138"><a href="#cb5-138" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> C-terminal repeat <span class="pp">|</span> 162–296 <span class="pp">|</span> Retained <span class="pp">|</span></span>
<span id="cb5-139"><a href="#cb5-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-140"><a href="#cb5-140" aria-hidden="true" tabindex="-1"></a>The boundaries were mapped from native 3BJX residue numbers to MSA columns.</span>
<span id="cb5-141"><a href="#cb5-141" aria-hidden="true" tabindex="-1"></a>The same columns were then extracted from every family member. All-gap columns</span>
<span id="cb5-142"><a href="#cb5-142" aria-hidden="true" tabindex="-1"></a>were removed independently from each resulting alignment. The procedure is</span>
<span id="cb5-143"><a href="#cb5-143" aria-hidden="true" tabindex="-1"></a>implemented in <span class="co">[</span><span class="ot">`split_dehi_msa.py`</span><span class="co">](split_dehi_msa.py)</span>.</span>
<span id="cb5-144"><a href="#cb5-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-145"><a href="#cb5-145" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Region <span class="pp">|</span> 3BJX residues <span class="pp">|</span> Source MSA columns <span class="pp">|</span> Output columns <span class="pp">|</span> Sequences <span class="pp">|</span></span>
<span id="cb5-146"><a href="#cb5-146" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|---:|</span></span>
<span id="cb5-147"><a href="#cb5-147" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> N <span class="pp">|</span> 1–129 <span class="pp">|</span> 16–154 <span class="pp">|</span> 139 <span class="pp">|</span> 69 <span class="pp">|</span></span>
<span id="cb5-148"><a href="#cb5-148" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Linker excluded <span class="pp">|</span> 130–161 <span class="pp">|</span> 155–217 <span class="pp">|</span> — <span class="pp">|</span> — <span class="pp">|</span></span>
<span id="cb5-149"><a href="#cb5-149" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> C <span class="pp">|</span> 162–296 <span class="pp">|</span> 218–384 <span class="pp">|</span> 167 <span class="pp">|</span> 69 <span class="pp">|</span></span>
<span id="cb5-150"><a href="#cb5-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-151"><a href="#cb5-151" aria-hidden="true" tabindex="-1"></a>: Structure-guided split of the DehI family alignment. {#tbl-split-summary}</span>
<span id="cb5-152"><a href="#cb5-152" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-153"><a href="#cb5-153" aria-hidden="true" tabindex="-1"></a>The N-terminal output has 139 aligned columns and the C-terminal output has</span>
<span id="cb5-154"><a href="#cb5-154" aria-hidden="true" tabindex="-1"></a><span class="ss">167. </span>The ungapped 3BJX fragments contain 129 and 135 residues, respectively.</span>
<span id="cb5-155"><a href="#cb5-155" aria-hidden="true" tabindex="-1"></a>All 69 input records are represented in both outputs.</span>
<span id="cb5-156"><a href="#cb5-156" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-157"><a href="#cb5-157" aria-hidden="true" tabindex="-1"></a><span class="fu">## HH-suite profile construction</span></span>
<span id="cb5-158"><a href="#cb5-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-159"><a href="#cb5-159" aria-hidden="true" tabindex="-1"></a>HH-suite was chosen because HHalign directly compares profile HMMs and is</span>
<span id="cb5-160"><a href="#cb5-160" aria-hidden="true" tabindex="-1"></a>designed to detect remote protein homology through alignment-to-alignment or</span>
<span id="cb5-161"><a href="#cb5-161" aria-hidden="true" tabindex="-1"></a>HMM-to-HMM comparison</span>
<span id="cb5-162"><a href="#cb5-162" aria-hidden="true" tabindex="-1"></a>(<span class="co">[</span><span class="ot">HH-suite documentation</span><span class="co">](https://github.com/soedinglab/hh-suite)</span>;</span>
<span id="cb5-163"><a href="#cb5-163" aria-hidden="true" tabindex="-1"></a><span class="co">[</span><span class="ot">Steinegger *et al.*, 2019</span><span class="co">](https://doi.org/10.1186/s12859-019-3019-7)</span>).</span>
<span id="cb5-164"><a href="#cb5-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-165"><a href="#cb5-165" aria-hidden="true" tabindex="-1"></a>Each split FASTA alignment was converted to A3M format. A column was designated</span>
<span id="cb5-166"><a href="#cb5-166" aria-hidden="true" tabindex="-1"></a>as a match state when fewer than 50% of sequences contained a gap (<span class="in">`-M 50`</span>).</span>
<span id="cb5-167"><a href="#cb5-167" aria-hidden="true" tabindex="-1"></a>Columns not meeting this condition were represented as insert states. HHmake</span>
<span id="cb5-168"><a href="#cb5-168" aria-hidden="true" tabindex="-1"></a>then applied its standard sequence filtering and weighting before constructing</span>
<span id="cb5-169"><a href="#cb5-169" aria-hidden="true" tabindex="-1"></a>each HHM.</span>
<span id="cb5-170"><a href="#cb5-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-171"><a href="#cb5-171" aria-hidden="true" tabindex="-1"></a><span class="in">```bash</span></span>
<span id="cb5-172"><a href="#cb5-172" aria-hidden="true" tabindex="-1"></a><span class="ex">reformat.pl</span> fas a3m results/dehi_N_terminal_msa.fasta <span class="dt">\</span></span>
<span id="cb5-173"><a href="#cb5-173" aria-hidden="true" tabindex="-1"></a>  results/dehi_N_terminal.a3m <span class="at">-M</span> 50</span>
<span id="cb5-174"><a href="#cb5-174" aria-hidden="true" tabindex="-1"></a><span class="ex">reformat.pl</span> fas a3m results/dehi_C_terminal_msa.fasta <span class="dt">\</span></span>
<span id="cb5-175"><a href="#cb5-175" aria-hidden="true" tabindex="-1"></a>  results/dehi_C_terminal.a3m <span class="at">-M</span> 50</span>
<span id="cb5-176"><a href="#cb5-176" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-177"><a href="#cb5-177" aria-hidden="true" tabindex="-1"></a><span class="ex">hhmake</span> <span class="at">-i</span> results/dehi_N_terminal.a3m <span class="dt">\</span></span>
<span id="cb5-178"><a href="#cb5-178" aria-hidden="true" tabindex="-1"></a>  <span class="at">-o</span> results/dehi_N_terminal.hhm <span class="at">-name</span> DehI_N_terminal</span>
<span id="cb5-179"><a href="#cb5-179" aria-hidden="true" tabindex="-1"></a><span class="ex">hhmake</span> <span class="at">-i</span> results/dehi_C_terminal.a3m <span class="dt">\</span></span>
<span id="cb5-180"><a href="#cb5-180" aria-hidden="true" tabindex="-1"></a>  <span class="at">-o</span> results/dehi_C_terminal.hhm <span class="at">-name</span> DehI_C_terminal</span>
<span id="cb5-181"><a href="#cb5-181" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-182"><a href="#cb5-182" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-183"><a href="#cb5-183" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Profile <span class="pp">|</span> Match states <span class="pp">|</span> Sequences retained <span class="pp">|</span> Effective sequences <span class="pp">|</span></span>
<span id="cb5-184"><a href="#cb5-184" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|---:|---:|</span></span>
<span id="cb5-185"><a href="#cb5-185" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> DehI N-terminal <span class="pp">|</span> 123 <span class="pp">|</span> 68/69 <span class="pp">|</span> 5.5 <span class="pp">|</span></span>
<span id="cb5-186"><a href="#cb5-186" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> DehI C-terminal <span class="pp">|</span> 113 <span class="pp">|</span> 68/69 <span class="pp">|</span> 6.0 <span class="pp">|</span></span>
<span id="cb5-187"><a href="#cb5-187" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-188"><a href="#cb5-188" aria-hidden="true" tabindex="-1"></a>: Properties of the two HH-suite profiles. {#tbl-profile-summary}</span>
<span id="cb5-189"><a href="#cb5-189" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-190"><a href="#cb5-190" aria-hidden="true" tabindex="-1"></a>HHmake retained 68 of 69 sequences in each model after its default redundancy</span>
<span id="cb5-191"><a href="#cb5-191" aria-hidden="true" tabindex="-1"></a>and quality filters. The effective sequence counts (<span class="in">`Neff`</span>) of 5.5 and 6.0 are</span>
<span id="cb5-192"><a href="#cb5-192" aria-hidden="true" tabindex="-1"></a>much smaller than the raw sequence count because related sequences do not</span>
<span id="cb5-193"><a href="#cb5-193" aria-hidden="true" tabindex="-1"></a>contribute as independent observations.</span>
<span id="cb5-194"><a href="#cb5-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-195"><a href="#cb5-195" aria-hidden="true" tabindex="-1"></a><span class="fu">## N-terminal versus C-terminal HHalign result</span></span>
<span id="cb5-196"><a href="#cb5-196" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-197"><a href="#cb5-197" aria-hidden="true" tabindex="-1"></a>The two precomputed HHMs were compared directly:</span>
<span id="cb5-198"><a href="#cb5-198" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-199"><a href="#cb5-199" aria-hidden="true" tabindex="-1"></a><span class="in">```bash</span></span>
<span id="cb5-200"><a href="#cb5-200" aria-hidden="true" tabindex="-1"></a><span class="ex">hhalign</span> <span class="dt">\</span></span>
<span id="cb5-201"><a href="#cb5-201" aria-hidden="true" tabindex="-1"></a>  <span class="at">-i</span> results/dehi_N_terminal.hhm <span class="dt">\</span></span>
<span id="cb5-202"><a href="#cb5-202" aria-hidden="true" tabindex="-1"></a>  <span class="at">-t</span> results/dehi_C_terminal.hhm <span class="dt">\</span></span>
<span id="cb5-203"><a href="#cb5-203" aria-hidden="true" tabindex="-1"></a>  <span class="at">-o</span> results/dehi_N_vs_C.hhr <span class="dt">\</span></span>
<span id="cb5-204"><a href="#cb5-204" aria-hidden="true" tabindex="-1"></a>  <span class="at">-Oa3m</span> results/dehi_N_vs_C.a3m <span class="dt">\</span></span>
<span id="cb5-205"><a href="#cb5-205" aria-hidden="true" tabindex="-1"></a>  <span class="at">-atab</span> results/dehi_N_vs_C.tsv</span>
<span id="cb5-206"><a href="#cb5-206" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-207"><a href="#cb5-207" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-208"><a href="#cb5-208" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Metric <span class="pp">|</span> Value <span class="pp">|</span></span>
<span id="cb5-209"><a href="#cb5-209" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|</span></span>
<span id="cb5-210"><a href="#cb5-210" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> HHalign probability <span class="pp">|</span> 99.54% <span class="pp">|</span></span>
<span id="cb5-211"><a href="#cb5-211" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> E-value <span class="pp">|</span> 2.9 × 10^-23^ <span class="pp">|</span></span>
<span id="cb5-212"><a href="#cb5-212" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Profile score <span class="pp">|</span> 124.39 bits <span class="pp">|</span></span>
<span id="cb5-213"><a href="#cb5-213" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Aligned columns <span class="pp">|</span> 108 <span class="pp">|</span></span>
<span id="cb5-214"><a href="#cb5-214" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Direct identity <span class="pp">|</span> 17% <span class="pp">|</span></span>
<span id="cb5-215"><a href="#cb5-215" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Profile similarity <span class="pp">|</span> 0.123 <span class="pp">|</span></span>
<span id="cb5-216"><a href="#cb5-216" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Sum of posterior probabilities <span class="pp">|</span> 94.6 <span class="pp">|</span></span>
<span id="cb5-217"><a href="#cb5-217" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> N-profile coverage <span class="pp">|</span> 87.8% <span class="pp">|</span></span>
<span id="cb5-218"><a href="#cb5-218" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> C-profile coverage <span class="pp">|</span> 95.6% <span class="pp">|</span></span>
<span id="cb5-219"><a href="#cb5-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-220"><a href="#cb5-220" aria-hidden="true" tabindex="-1"></a>: HHalign profile-profile comparison. {#tbl-hhalign-summary}</span>
<span id="cb5-221"><a href="#cb5-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-222"><a href="#cb5-222" aria-hidden="true" tabindex="-1"></a>The alignment spans N-profile match states 5–113 and C-profile match states</span>
<span id="cb5-223"><a href="#cb5-223" aria-hidden="true" tabindex="-1"></a>2–112. It therefore covers most of both models rather than selecting a small</span>
<span id="cb5-224"><a href="#cb5-224" aria-hidden="true" tabindex="-1"></a>highly conserved segment. The 17% direct identity lies in the range where</span>
<span id="cb5-225"><a href="#cb5-225" aria-hidden="true" tabindex="-1"></a>pairwise sequence comparison alone is generally difficult, while the profile</span>
<span id="cb5-226"><a href="#cb5-226" aria-hidden="true" tabindex="-1"></a>score remains strong because residue preferences and gap patterns are</span>
<span id="cb5-227"><a href="#cb5-227" aria-hidden="true" tabindex="-1"></a>aggregated across the family.</span>
<span id="cb5-228"><a href="#cb5-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-229"><a href="#cb5-229" aria-hidden="true" tabindex="-1"></a><span class="fu">### Profile-profile alignment</span></span>
<span id="cb5-230"><a href="#cb5-230" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-231"><a href="#cb5-231" aria-hidden="true" tabindex="-1"></a>The following is the consensus and 3BJX portion of the HHalign output. Digits in</span>
<span id="cb5-232"><a href="#cb5-232" aria-hidden="true" tabindex="-1"></a>the <span class="in">`Confidence`</span> lines are posterior alignment confidence on a 0–9 scale.</span>
<span id="cb5-233"><a href="#cb5-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-234"><a href="#cb5-234" aria-hidden="true" tabindex="-1"></a><span class="in">```text</span></span>
<span id="cb5-235"><a href="#cb5-235" aria-hidden="true" tabindex="-1"></a><span class="in">Q 3BJX       12 QLDVSGEMESTYEDIRLTLRVPWVAFGCRVLATFPGYLPLAWRR.SAEALITRYAEQAADELRERSLLNIGPLPNL-K-E 88 (129)</span></span>
<span id="cb5-236"><a href="#cb5-236" aria-hidden="true" tabindex="-1"></a><span class="in">Q Consensus   5 e~eA~g~~~~vY~DIk~tLrVP~Vn~ifRtlA~yp~fl~~~W~~.~rP~~~T~~fe~aA~~lR~~~~~~~~~~~~~-~-~ 81 (123)</span></span>
<span id="cb5-237"><a href="#cb5-237" aria-hidden="true" tabindex="-1"></a><span class="in">                +.++.+.++++|+|||+++|.|.||..+|+||+||+||..+|+. +||..+|.+|++++++++..+...+...+-+ . .</span></span>
<span id="cb5-238"><a href="#cb5-238" aria-hidden="true" tabindex="-1"></a><span class="in">T Consensus   2 ~~~~~~~~~~l~~dI~~~h~~~~v~SdYR~LA~wP~~L~~~W~~.LkP~i~s~~y~~~~~~l~~~A~~~v~~lP~~v~l~ 80 (113)</span></span>
<span id="cb5-239"><a href="#cb5-239" aria-hidden="true" tabindex="-1"></a><span class="in">T 3BJX        2 ATKASTEVQGLLKRVADLHYHHGPASDFQALANWPKVLQIVTDEvLAPVARTEQYDAKSRELVTRARELVRGLPGSAGVQ 81 (135)</span></span>
<span id="cb5-240"><a href="#cb5-240" aria-hidden="true" tabindex="-1"></a><span class="in">Confidence      56889999999999999999999999999999999999999999 9999999999999999999888877765332 1 1</span></span>
<span id="cb5-241"><a href="#cb5-241" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-242"><a href="#cb5-242" aria-hidden="true" tabindex="-1"></a><span class="in">Q 3BJX       89 --RLYAAGFDDGEIEKVRRVLYAFNYGNPKYLL 119 (129)</span></span>
<span id="cb5-243"><a href="#cb5-243" aria-hidden="true" tabindex="-1"></a><span class="in">Q Consensus  82 ~-~~~~~~~~~~~~~~ir~~l~~f~~vnPklLl 113 (123)</span></span>
<span id="cb5-244"><a href="#cb5-244" aria-hidden="true" tabindex="-1"></a><span class="in">                 . .+.+.+ ++.++++|.+.+..|...-|-++|</span></span>
<span id="cb5-245"><a href="#cb5-245" aria-hidden="true" tabindex="-1"></a><span class="in">T Consensus  81 ~~~L~~~~-~~~~i~~i~~l~~~F~~~lp~Lil 112 (113)</span></span>
<span id="cb5-246"><a href="#cb5-246" aria-hidden="true" tabindex="-1"></a><span class="in">T 3BJX       82 RSELMSML-TPNELAGLTGVLFMYQRFIADITI 113 (135)</span></span>
<span id="cb5-247"><a href="#cb5-247" aria-hidden="true" tabindex="-1"></a><span class="in">Confidence      1 555555 899999999999999988877654</span></span>
<span id="cb5-248"><a href="#cb5-248" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb5-249"><a href="#cb5-249" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-250"><a href="#cb5-250" aria-hidden="true" tabindex="-1"></a><span class="fu">## Interpretation</span></span>
<span id="cb5-251"><a href="#cb5-251" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-252"><a href="#cb5-252" aria-hidden="true" tabindex="-1"></a>Three features make this result supportive of internal homology:</span>
<span id="cb5-253"><a href="#cb5-253" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-254"><a href="#cb5-254" aria-hidden="true" tabindex="-1"></a><span class="ss">1. </span>**High profile probability.** HHalign assigns a 99.54% probability to the</span>
<span id="cb5-255"><a href="#cb5-255" aria-hidden="true" tabindex="-1"></a>   N/C relationship.</span>
<span id="cb5-256"><a href="#cb5-256" aria-hidden="true" tabindex="-1"></a><span class="ss">2. </span>**Domain-scale coverage.** The 108 aligned columns cover 88% of the N model</span>
<span id="cb5-257"><a href="#cb5-257" aria-hidden="true" tabindex="-1"></a>   and 96% of the C model.</span>
<span id="cb5-258"><a href="#cb5-258" aria-hidden="true" tabindex="-1"></a><span class="ss">3. </span>**Remote rather than trivial similarity.** Direct identity is only 17%, yet</span>
<span id="cb5-259"><a href="#cb5-259" aria-hidden="true" tabindex="-1"></a>   conserved residue patterns remain detectable when information is combined</span>
<span id="cb5-260"><a href="#cb5-260" aria-hidden="true" tabindex="-1"></a>   across 69 family members.</span>
<span id="cb5-261"><a href="#cb5-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-262"><a href="#cb5-262" aria-hidden="true" tabindex="-1"></a>Together with the near-identical structural folds reported for 3BJX, this is</span>
<span id="cb5-263"><a href="#cb5-263" aria-hidden="true" tabindex="-1"></a>consistent with the proposal that an ancestral domain duplicated in tandem and</span>
<span id="cb5-264"><a href="#cb5-264" aria-hidden="true" tabindex="-1"></a>the two copies subsequently diverged while remaining fused in DehI.</span>
<span id="cb5-265"><a href="#cb5-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-266"><a href="#cb5-266" aria-hidden="true" tabindex="-1"></a>::: {.callout-note title="What the result does not prove"}</span>
<span id="cb5-267"><a href="#cb5-267" aria-hidden="true" tabindex="-1"></a>HHalign measures compatibility between two profile models. It does not by</span>
<span id="cb5-268"><a href="#cb5-268" aria-hidden="true" tabindex="-1"></a>itself date the duplication, identify the ancestral free-standing family, or</span>
<span id="cb5-269"><a href="#cb5-269" aria-hidden="true" tabindex="-1"></a>exclude every alternative evolutionary scenario. Structural correspondence,</span>
<span id="cb5-270"><a href="#cb5-270" aria-hidden="true" tabindex="-1"></a>taxonomic distribution, conserved catalytic residues, and comparisons with</span>
<span id="cb5-271"><a href="#cb5-271" aria-hidden="true" tabindex="-1"></a>external families provide independent evidence.</span>
<span id="cb5-272"><a href="#cb5-272" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb5-273"><a href="#cb5-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-274"><a href="#cb5-274" aria-hidden="true" tabindex="-1"></a><span class="fu">### Statistical qualification</span></span>
<span id="cb5-275"><a href="#cb5-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-276"><a href="#cb5-276" aria-hidden="true" tabindex="-1"></a>Only one template HMM was searched (<span class="in">`Searched_HMMs 1`</span>). Consequently, the</span>
<span id="cb5-277"><a href="#cb5-277" aria-hidden="true" tabindex="-1"></a>reported E-value and P-value are identical (<span class="in">`2.9 × 10^-23^`</span>); this is not an</span>
<span id="cb5-278"><a href="#cb5-278" aria-hidden="true" tabindex="-1"></a>E-value corrected for a large profile database. The probability, score, and</span>
<span id="cb5-279"><a href="#cb5-279" aria-hidden="true" tabindex="-1"></a>especially the broad alignment coverage remain directly informative for this</span>
<span id="cb5-280"><a href="#cb5-280" aria-hidden="true" tabindex="-1"></a>pre-specified N-versus-C comparison.</span>
<span id="cb5-281"><a href="#cb5-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-282"><a href="#cb5-282" aria-hidden="true" tabindex="-1"></a>Secondary structure was not included in the HHalign score (<span class="in">`SS = 0`</span>, reported</span>
<span id="cb5-283"><a href="#cb5-283" aria-hidden="true" tabindex="-1"></a>as <span class="in">`missing dssp`</span>). This makes the profile match a sequence-derived result</span>
<span id="cb5-284"><a href="#cb5-284" aria-hidden="true" tabindex="-1"></a>rather than one driven by the known structural similarity.</span>
<span id="cb5-285"><a href="#cb5-285" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-286"><a href="#cb5-286" aria-hidden="true" tabindex="-1"></a><span class="fu">## Robustness checks and next analyses</span></span>
<span id="cb5-287"><a href="#cb5-287" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-288"><a href="#cb5-288" aria-hidden="true" tabindex="-1"></a>The following tests would strengthen the evolutionary interpretation:</span>
<span id="cb5-289"><a href="#cb5-289" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-290"><a href="#cb5-290" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Rebuild both profiles after removing 3BJX and repeat the comparison, ensuring</span>
<span id="cb5-291"><a href="#cb5-291" aria-hidden="true" tabindex="-1"></a>  that the structural reference is not driving the result.</span>
<span id="cb5-292"><a href="#cb5-292" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Repeat profile construction with match-state thresholds of 30%, 50%, and 70%</span>
<span id="cb5-293"><a href="#cb5-293" aria-hidden="true" tabindex="-1"></a>  gaps and compare the aligned cores.</span>
<span id="cb5-294"><a href="#cb5-294" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Construct independent CMD and AhpD HHMs, then compare DehI-N and DehI-C to</span>
<span id="cb5-295"><a href="#cb5-295" aria-hidden="true" tabindex="-1"></a>  each external family.</span>
<span id="cb5-296"><a href="#cb5-296" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Search both DehI profiles against the same curated HH-suite database and test</span>
<span id="cb5-297"><a href="#cb5-297" aria-hidden="true" tabindex="-1"></a>  whether their strongest domain-level matches overlap.</span>
<span id="cb5-298"><a href="#cb5-298" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>Map conserved aligned profile positions back onto the 3BJX structure and</span>
<span id="cb5-299"><a href="#cb5-299" aria-hidden="true" tabindex="-1"></a>  determine whether they occupy corresponding structural environments.</span>
<span id="cb5-300"><a href="#cb5-300" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-301"><a href="#cb5-301" aria-hidden="true" tabindex="-1"></a>The four most direct cross-family comparisons are:</span>
<span id="cb5-302"><a href="#cb5-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-303"><a href="#cb5-303" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Query profile <span class="pp">|</span> Template profile <span class="pp">|</span> Question <span class="pp">|</span></span>
<span id="cb5-304"><a href="#cb5-304" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---|---|</span></span>
<span id="cb5-305"><a href="#cb5-305" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> DehI-N <span class="pp">|</span> CMD <span class="pp">|</span> Does the N repeat resemble a free-standing CMD-like fold? <span class="pp">|</span></span>
<span id="cb5-306"><a href="#cb5-306" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> DehI-C <span class="pp">|</span> CMD <span class="pp">|</span> Does the C repeat show the same relationship? <span class="pp">|</span></span>
<span id="cb5-307"><a href="#cb5-307" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> DehI-N <span class="pp">|</span> AhpD <span class="pp">|</span> Does the N repeat resemble the AhpD family? <span class="pp">|</span></span>
<span id="cb5-308"><a href="#cb5-308" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> DehI-C <span class="pp">|</span> AhpD <span class="pp">|</span> Does the C repeat show the same relationship? <span class="pp">|</span></span>
<span id="cb5-309"><a href="#cb5-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-310"><a href="#cb5-310" aria-hidden="true" tabindex="-1"></a>Agreement across both halves and an external family would provide stronger</span>
<span id="cb5-311"><a href="#cb5-311" aria-hidden="true" tabindex="-1"></a>evidence about the ancestry of the duplicated unit than the internal N/C result</span>
<span id="cb5-312"><a href="#cb5-312" aria-hidden="true" tabindex="-1"></a>alone.</span>
<span id="cb5-313"><a href="#cb5-313" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-314"><a href="#cb5-314" aria-hidden="true" tabindex="-1"></a><span class="fu">## Reproducibility and downloads</span></span>
<span id="cb5-315"><a href="#cb5-315" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-316"><a href="#cb5-316" aria-hidden="true" tabindex="-1"></a>The report uses precomputed HH-suite output so that the website can be rendered</span>
<span id="cb5-317"><a href="#cb5-317" aria-hidden="true" tabindex="-1"></a>without installing native bioinformatics software. The Python dependencies are</span>
<span id="cb5-318"><a href="#cb5-318" aria-hidden="true" tabindex="-1"></a>managed by <span class="in">`uv`</span>; HH-suite 3 is required only when regenerating the profiles.</span>
<span id="cb5-319"><a href="#cb5-319" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-320"><a href="#cb5-320" aria-hidden="true" tabindex="-1"></a><span class="fu">### Scripts</span></span>
<span id="cb5-321"><a href="#cb5-321" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-322"><a href="#cb5-322" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">`split_dehi_msa.py`</span><span class="co">](split_dehi_msa.py)</span> — map the 3BJX boundaries through</span>
<span id="cb5-323"><a href="#cb5-323" aria-hidden="true" tabindex="-1"></a>  the family MSA and extract both repeats.</span>
<span id="cb5-324"><a href="#cb5-324" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">`build_dehi_hhsuite_profiles.sh`</span><span class="co">](build_dehi_hhsuite_profiles.sh)</span> — convert</span>
<span id="cb5-325"><a href="#cb5-325" aria-hidden="true" tabindex="-1"></a>  the alignments to A3M, construct both HHMs, and run HHalign.</span>
<span id="cb5-326"><a href="#cb5-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-327"><a href="#cb5-327" aria-hidden="true" tabindex="-1"></a><span class="fu">### Alignments and sequences</span></span>
<span id="cb5-328"><a href="#cb5-328" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-329"><a href="#cb5-329" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Full DehI core MSA</span><span class="co">](results/dehi_core_msa.fasta)</span></span>
<span id="cb5-330"><a href="#cb5-330" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">N-terminal aligned FASTA</span><span class="co">](results/dehi_N_terminal_msa.fasta)</span></span>
<span id="cb5-331"><a href="#cb5-331" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">C-terminal aligned FASTA</span><span class="co">](results/dehi_C_terminal_msa.fasta)</span></span>
<span id="cb5-332"><a href="#cb5-332" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">N-terminal ungapped FASTA</span><span class="co">](results/dehi_N_terminal.fasta)</span></span>
<span id="cb5-333"><a href="#cb5-333" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">C-terminal ungapped FASTA</span><span class="co">](results/dehi_C_terminal.fasta)</span></span>
<span id="cb5-334"><a href="#cb5-334" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">N-terminal A3M</span><span class="co">](results/dehi_N_terminal.a3m)</span></span>
<span id="cb5-335"><a href="#cb5-335" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">C-terminal A3M</span><span class="co">](results/dehi_C_terminal.a3m)</span></span>
<span id="cb5-336"><a href="#cb5-336" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-337"><a href="#cb5-337" aria-hidden="true" tabindex="-1"></a><span class="fu">### Profiles and comparison output</span></span>
<span id="cb5-338"><a href="#cb5-338" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-339"><a href="#cb5-339" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">N-terminal HHM</span><span class="co">](results/dehi_N_terminal.hhm)</span></span>
<span id="cb5-340"><a href="#cb5-340" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">C-terminal HHM</span><span class="co">](results/dehi_C_terminal.hhm)</span></span>
<span id="cb5-341"><a href="#cb5-341" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">HHalign report</span><span class="co">](results/dehi_N_vs_C.hhr)</span></span>
<span id="cb5-342"><a href="#cb5-342" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">HHalign pairwise A3M</span><span class="co">](results/dehi_N_vs_C.a3m)</span></span>
<span id="cb5-343"><a href="#cb5-343" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">HHalign per-column table</span><span class="co">](results/dehi_N_vs_C.tsv)</span></span>
<span id="cb5-344"><a href="#cb5-344" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span><span class="co">[</span><span class="ot">Domain-splitting report</span><span class="co">](results/dehi_terminal_split_report.tsv)</span></span>
<span id="cb5-345"><a href="#cb5-345" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-346"><a href="#cb5-346" aria-hidden="true" tabindex="-1"></a>To regenerate the derived files locally:</span>
<span id="cb5-347"><a href="#cb5-347" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-348"><a href="#cb5-348" aria-hidden="true" tabindex="-1"></a><span class="in">```bash</span></span>
<span id="cb5-349"><a href="#cb5-349" aria-hidden="true" tabindex="-1"></a><span class="ex">uv</span> run python split_dehi_msa.py</span>
<span id="cb5-350"><a href="#cb5-350" aria-hidden="true" tabindex="-1"></a><span class="ex">./build_dehi_hhsuite_profiles.sh</span></span>
<span id="cb5-351"><a href="#cb5-351" aria-hidden="true" tabindex="-1"></a><span class="ex">quarto</span> render report.qmd</span>
<span id="cb5-352"><a href="#cb5-352" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
</code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->




<script src="report_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>